#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <directory>"
  exit 1
fi

fpath="$1"
dirnm=${fpath##*/}

mp3path="$fpath/../$dirnm.mp3"

cd "$1"
touch "$mp3path"



for f in *.mp3; do 
  echo "file '$f'" >> files;
done

ffmpeg -f concat -safe 0 -i files -c copy "$mp3path"

rm "$1/files"
