#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <directory>"
  exit 1
fi

#copies all mp3 files to a playlist directory and compiles a local .m3u file
#assumes the files in the directory given are all mp3 files

rm "$1.m3u"
touch "$1.m3u"
cd "$1"

m3u_path="../$1.m3u"

for f in *.mp3; do
    echo "Added: $f"
    echo "$1/$f" >> m3u_path
done

echo "Done"
