#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <url> <location>"
  exit 1
fi

mkdir -p "$2"

echo "Beginning to download playlist"

yt-dlp -o "$2/%(playlist_index)s - %(title)s.%(ext)s" -t mp3 --embed-thumbnail "$1"
echo "Downloaded playlist at: $1 to: $2"
